[pytest]
addopts = --strict-markers --disable-warnings --maxfail=3
markers = smoke: This is smoke test marker
          regression : This is a regression test marker
          sanity : This is a sanity test marker
          unit : marks unit tests
log_file = pytest.log

testpaths = tests
python_files = test_*.py